### ISSUE TITLE
LogLabelProvider appsettings

### ISSUE THREAD

**Issue by DanielUhlik** [josephwoodward/Serilog-Sinks-Loki#44]
Hi,

i have following settings in `appsettings.yml`
```yml
Serilog:
  MinimumLevel:
    Default: Information
    Override:
        Microsoft: Warning
        Microsoft.Hosting.Lifetime: Information
        Microsoft.EntityFrameworkCore.Database.Command: Error
  Using:
    - Serilog.Sinks.Loki
  Enrich:
    - FromLogContext
  WriteTo:
    - Name: LokiHttp
      Args:
        serverUrl: http://loki_url:3100
        labelProvider: UserManager.Api.LogLabelProvider, UserManager.Api
    - Name: Console
```

and following `LogLabelProvider`
```c#
using System.Collections.Generic;
using Serilog.Sinks.Loki.Labels;

namespace UserManager.Api
{
    public class LogLabelProvider : ILogLabelProvider
    {
        public IList<LokiLabel> GetLabels()
        {
            return new List<LokiLabel>
            {
                new ("microservice", "user-manager")
            };
        }
    }
}
```

Everything works great except labels. `LogLabelProvider` stays ignored and no global labels are attached. Any suggestions?
